#nginx image
FROM nginx:latest

# copy 5up files
COPY ./5up/html5up-aerial /usr/share/nginx/html

# create keys
RUN mkdir /var/keys
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /var/keys/ssl.key -out /var/keys/ssl.crt -subj "/C=BE/ST=Namur/L=Wallonie/O=undefined/CN=www.undefinedcontainer.com"
COPY ./files/config/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 443