FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install flask
RUN mkdir /app
COPY ./files/app.py /app/app.py
ENV FLASK_APP=/app/app.py
EXPOSE 8000
CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]