#!/bin/bash
#run by typing "bash start" in the terminal

# building image
docker build -t metasploit .

# run the container 
docker run -p 127.0.0.1:80:80 -p 127.0.0.1:443:443 --name metasploit -it metasploit bash -c "service postgresql start && msfdb init && msfconsole"
