FROM nginx:latest

# Install necessary packages
RUN apt-get update && apt-get install -y openssh-server openssl git rsyslog

# Configure SSH
RUN mkdir /var/run/sshd \
    && echo 'root:12OKQ8jqsd9!qsd' | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]

# Create key directory & keys
WORKDIR /var/keys
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ssl.key -out ssl.crt -subj "/C=BE/ST=Namur/L=Wallonie/O=undefined/CN=www.undefinedcontainer.com"

# Copy NGINX configuration file
COPY ./config/nginx.conf /etc/nginx/conf.d/honey.conf

# Set working directory for NGINX content
WORKDIR /usr/share/nginx/html

# Copy files
COPY ./files .

# Expose ports
EXPOSE 443
EXPOSE 22