FROM nginx:latest

RUN apt-get update && apt-get install -y openssh-server openssl git rsyslog

# Configure SSH
RUN mkdir /var/run/sshd
RUN echo 'root:12OKQ8jqsd9!qsd' | chpasswd


#password for user login
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]

# Create /code directory and set it as the working directory
WORKDIR /usr/share/nginx/html

COPY ./files .

# Create key directory & keys
WORKDIR /var/keys
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ssl.key -out ssl.crt -subj "/C=BE/ST=Namur/L=Wallonie/O=undefined/CN=www.undefinedcontainer.com"

# Copy the nginx configuration file
COPY .//config/nginx.conf /etc/nginx/conf.d/default.conf

# expose the ports
EXPOSE 443
EXPOSE 80
EXPOSE 22