#nginx image
FROM nginx:latest

#copy index and 404 pages
COPY ./files/index.html /usr/share/nginx/html/index.html
COPY ./files/404.html /usr/share/nginx/html/404.html

#create assets dirs
RUN mkdir /usr/share/nginx/html/assets
RUN mkdir /usr/share/nginx/html/assets/js

#copy stylesheets
COPY ./files/assets/style.css /usr/share/nginx/html/assets/style.css
COPY ./files/assets/404.css /usr/share/nginx/html/assets/404.css

# Change nginx configuration to work with SSL
COPY ./files/config/nginx.conf /etc/nginx/conf.d/default.conf
