#nginx image
FROM nginx:latest

#copy index and 404 pages
COPY ./files/index.html /usr/share/nginx/html/index.html
COPY ./files/404.html /usr/share/nginx/html/404.html

#create assets dirs
RUN mkdir /usr/share/nginx/html/assets
RUN mkdir /usr/share/nginx/html/assets/js

#copy stylesheets
COPY ./files/assets/style.css /usr/share/nginx/html/assets/style.css
COPY ./files/assets/404.css /usr/share/nginx/html/assets/404.css

#And now, HTTPS
RUN mkdir /var/keys
#generate openssl key and cert
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /var/keys/ssl.key -out /var/keys/ssl.crt -subj "/C=BE/ST=Namur/L=Wallonie/O=undefined/CN=www.undefinedcontainer.com"
COPY ./files/config/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 443
