#!/bin/bash
#run by typing "bash start" in the terminal

# building image
docker build -t webserver .

# run the container 
docker run -d -p 127.0.0.1:80:80 -p 127.0.0.1:443:443 --name webserver webserver
